### ISSUE TITLE
angriffe nicht abgeschickt..

### ISSUE THREAD

**Issue by st4bel** [st4bel/DS_Timer#20]
komisches Verhalten: 
3 geplante angriffe innerhalb einer sekunde, 
1 wurde in `trash` verschoben (allerdings nicht der erste der angriffe)
die anderen 2 angriffe sind noch `schedule` ordner
in log datei steht überhaupt nichts von den angriffen.

**Comment by st4bel** [comment]
anscheinend ging das losschicken allgemein nicht, nach einem neustart wurde alle geplanten nicht abgeschickten angriffe sofort losgeschickt. jetzt funktioniert es vorerst wieder normal

**Comment by JoahTheron** [comment]
kann geschlossen werden. nicht mehr relevant mit der aktuellen version.
