### ISSUE TITLE
verwendung kombinierter Parameter für Truppenzahlangaben

### ISSUE THREAD

**Issue by st4bel** [st4bel/DS_Timer#3]
als Parameter sind z.B. =x, >=x, *, -x, x gemeint.

eine Kombination dieser PArameter würde sich in einigen Fällen anbieten, oder wäre sogar überaus praktisch;

`200, >=100`

würde dementsprechend bedeuten: schicke 200, falls nur weniger da sind, schicke alle, die da sind, außer es sind weniger als 100 da

einige Kombinationen sind unsinnig: alles mimt =x oder \* ist nicht möglich
aber kombination von x oder -x mit >=x wären denkbar.

**Comment by syxolk** [comment]
Alle Möglichkeiten (Mit _Nö_ markierte sind eher doof):
- `=x >=y` Nö
- `=x *` Nö
- `=x -y` Nö
- `=x y` Nö
- `>=x *` Jop (Bringt aber nix)
- `>=x -x` Jop
- `>=x y` Jop
- `* -x` Jop (Bringt aber nix)
- `* x` Jop (Bringt aber nix)
- `-x y` Jop (Bringt aber nix)

**Comment by st4bel** [comment]
format 

`x, >=y`

komma, beliebig viele leerzeichen
