### ISSUE TITLE
eigener Versions parser

### ISSUE THREAD

**Issue by st4bel** [st4bel/DS_Timer#40]
in #39 wurde `version_parser` verwendet, welcher nur bis build version aka 0.4.**8** parsen kann
why auch ever

**Comment by syxolk** [comment]
deswegen: https://semver.org/ D.h. standardmäßig gibt es nur "MAJOR.MINOR.PATCH"

**Comment by st4bel** [comment]
ne das wäre zu einfach sich an standards zu halten
