### ISSUE TITLE
ERROR	'sitter'

### ISSUE THREAD

**Issue by MickLesk** [st4bel/DS_Timer#73]
1. Wenn ich HTML vom WB Importiere, so wird kein einziger angriff geschickt. 

2. Nach Import des DSKeks kommt immer folgende Meldung, manchmal klappt abschicken, manchmal nicht. 
Session-IDs fehlerhaft:
de185 USERNAME: Nicht importiert

**Comment by st4bel** [comment]
hiho... version?

1. wie sieht dein wb import aus?
2. wird in nächster version gefixt / ist gefixt

danke für die rückmeldung

**Comment by MickLesk** [comment]
Moin,

ist der normale HTML-Import. Dauert ne weile funktioniert meist aber.
WB 3.7.2

Hab auch den Text-Import probiert, genau das gleiche.

**Comment by st4bel** [comment]
ok.. welche timer version benutzt du? 0.6.6 oder älter? oder master?

würdest du mal einen auszug eines wb-Exports hier posten. gerne annonymisiert. außerdem brauch ich den Server (de100), da es einige welten mit "innovativen" einstellungen seitens innogames gibt

also wb-import ansich funktioniert, aber abgeschickt wird nicht?

wurden andere angriffe abschicken, die anders importiert wurden (export-userscript, erstellen des Angriffs auf der Timer-Oberfläche)?

können das gespräch auch gerne auf meinen "support" discord oder Teamspeak verlagern. weiß ja nicht wie gut du dich mit dem timer / allgemein mit programmieren auskennst:
[discord](https://discord.gg/HZQ5yAV63A)
ts3: ---

**Comment by MickLesk** [comment]
Jo habe die 0.6.6 hatte keine Lust mir das selber zu builden :D 

Entweder schick ich es dir auf Discord, am liebsten aber per Mail. 

Genau import geht, Template ist da mit den Truppen, kommt aber immer dieser Error, ich habe mir die Mühe gemacht und vor 4 Tagen alles manuell eingebaut, das ging ohne Probleme. (Also Versammlungsplatz, Truppen angeben -> Export.)

**Comment by st4bel** [comment]
Mail würde ich nur ungern hier veröffentlichen, discordlink ist ja da. bis dahin

Fehler mit dem timer sind leider aufgrund meiner unfähigkeit guten code zu schreiben meist von vielen dingen abhängig... dementsprechend muss ich immer einiges mit den usern durchsprechen :)
